### ISSUE TITLE
Add team, project & footer section

### ISSUE THREAD

**Issue by vinzvinci** [surpathcommunity/surpathcommunity.github.io#12]
**To Do:**
- [x] Add footer section (copyrights included)
- [x] Add 6 cards at team section `(included my card already)` 
- [x] Add my profile pic & tagline at team section `(get it in my github profile)`
- [ ] Add **Project** at navbar
- [ ] Add 4 cards at project section

**Comment by Bryson69** [comment]
I will gladly do this

**Comment by vinzvinci** [comment]
Sure, thank you :)
