### ISSUE TITLE
Add info. about SurPath & make a proposal design for the page

### ISSUE THREAD

**Issue by vinzvinci** [surpathcommunity/surpathcommunity.github.io#6]
To do:
- Create **about.html**
- Propose an idea about the design
- Add information about SurPath

~~-~~
About
**SurPath** is an welcoming and inclusive open source community that helps every aspiring student or career shifter in the Philippines. We are here to learn, get along with your passion and know your expertise in the field. Members of the community will be able to get a chance to get swag, to join some events, to get access on learning platforms and etc.
 
FAQs
`Who can join to the community?`
Any aspiring student or career shifter. Open Source is for everyone, It doesn't matter who you are, everyone will love you, and will appreciate your idea even it is small. Even if you dropout of college because of financial problems or even you have zero knowledge, we will help you to grow and getting you into tech industry. 
~~-~~

`What do you think about this? Have an idea? Comment below`

**Comment by Bryson69** [comment]
This is a great idea

**Comment by vinzvinci** [comment]
Thanks @Bryson69

**Comment by Bryson69** [comment]
I will do this and get back to you.

**Comment by vinzvinci** [comment]
Okay cool, take your time :)

**Comment by Bryson69** [comment]
The design for the about page
![About Page](https://user-images.githubusercontent.com/62892010/113801650-f00df300-9761-11eb-9953-2288cce6f1fe.png)

**Comment by vinzvinci** [comment]
Cool, I already merge #7. Thanks

**Comment by Bryson69** [comment]
No worries
