### ISSUE TITLE
Add the join us section

### ISSUE THREAD

**Issue by Bryson69** [surpathcommunity/surpathcommunity.github.io#8]
**Additional context**
Add this section in order for users to connect directly to the discord server

![Join Us](https://user-images.githubusercontent.com/62892010/113858794-d04fec80-97ac-11eb-9830-9a48f7bb1d99.png)

**Comment by vinzvinci** [comment]
There should be link for GitHub Organization and Discord Server

**Comment by vinzvinci** [comment]
Discord: https://discord.com/invite/RATJsSGM9d

GitHub: https://github.com/surpathcommunity
